### ISSUE TITLE
plug.kak related section in readme

### ISSUE THREAD

**Issue by andreyorst** [dmerejkowsky/kak-spell#6]
It is recommended to wrap up configuration of the plugin in `config` block if you're using `plug` command. This way plug.kak will make sure to secure loading of Kakoune, by using `try` `catch` blocks, so in case something is wrong with the package, e.g. breaking change removed some variables, or plugin is simply is not installed, Kakoune will be loaded normally, and a warning would appear in `*debug*`. My suggestion would be to simply mention `config` or provide an example snippet. If your plugin defines modules, you should use `defer module-name` block instead of `config`, so the `plug` would not try to apply not yet existing configurations.

**Comment by dmerejkowsky** [comment]
Hum - you seem to be describing a feature of `plug.kak` I did not know existed :P 

So I'm gonna read the fine documentation and then update the README accordingly.

Thanks for letting me know !

**Comment by andreyorst** [comment]
> Hum - you seem to be describing a feature of `plug.kak` I did not know existed :P
> 
> So I'm gonna read the fine documentation and then update the README accordingly.
> 
> Thanks for letting me know !

Feel free to look at my [plugin configuration file](https://github.com/andreyorst/dotfiles/blob/master/.config/kak/plugins.kak) that has all kind of configuration examples :slightly_smiling_face: . I'm using development branch of plug.kak, but everything should work on master version except for `plug_profile`.

**Comment by dmerejkowsky** [comment]
OK - doc was clear enough - your work on plug.kak is excellent btw. I'll add an explicit `config` keyword for the sake of readability.
